---
require:
  - rubocop-rspec

AllCops:
    NewCops: enable
    TargetRubyVersion: 3.2

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EndOfLine:
   EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Layout/LineLength:
    Max: 120
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'

Metrics/BlockLength:
    Max: 40

RSpec/Capybara:
    Exclude:
        - 'spec/features/**/*'

RSpec/MultipleExpectations:
    Max: 3
    Exclude:
        - 'spec/features/**/*'

RSpec/ExampleLength:
    Max: 10
    Exclude:
        - 'spec/features/**/*'

RSpec/MultipleMemoizedHelpers:
    Enabled: false

RSpec/VariableName:
    Enabled: false

Naming/VariableNumber:
    Enabled: false

Lint/MissingSuper:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false
